Population under devolution deal in England
GSS-Cogs/provider-ons-ess pull request #53
Opened 2023-02-23 10:48 UTC by santhosh-thangavel

New config file with Mission, Category and Indicator set to false.
Wrangling.py is added
csv file based on new config file
Added metadata with information from data_dictionary

#issue23

2023-02-24 13:32 UTC, sazzadur-ons commented on population-under-devolution-deal-in-england/wrangling.py
> +    df["Period"] = df.Period.str.replace(" January " , "-01-")
df["Period"] = df.Period.str.replace(" January " , "-01-") not required. Because pd.to_datetime(df["Period"]) converts to "YYYY-MM-DD' format.

2023-02-24 13:37 UTC, sazzadur-ons commented on population-under-devolution-deal-in-england/population-under-devolution-deal-in-england.json
> +        "united-kingdom"
"misssion-12"  in keywords

2023-02-24 13:41 UTC, sazzadur-ons commented on population-under-devolution-deal-in-england/population-under-devolution-deal-in-england.json
> +        "sub-national-data"
"thesmes": "https://www.ons.gov.uk/peoplepopulationandcommunity"

2023-02-24 13:42 UTC, sazzadur-ons reviewed
keywords, themes, and wrangling.py

2023-02-24 16:29 UTC, sazzadur-ons commented on population-under-devolution-deal-in-england/population-under-devolution-deal-in-england.json
> +    "description": "## Percentage of the population living in an area covered by the highest level of devolution.  \nThe indicator is: Population under devolution deal in England.\nThe Levelling Up c
In the description  it says ' \nThe Mission is 12(expand with information on what mission 12 means)'.
So, needd to describe what is mission 12

2023-02-24 16:30 UTC, sazzadur-ons requested changes
Commented on Description about misson 12

2023-02-27 10:44 UTC, santhosh-thangavel commented on population-under-devolution-deal-in-england/wrangling.py
> +    df["Period"] = df.Period.str.replace(" January " , "-01-")
Deleted unwanted code

2023-02-27 10:45 UTC, santhosh-thangavel commented on population-under-devolution-deal-in-england/population-under-devolution-deal-in-england.json
> +        "sub-national-data"
Added new themes URL.

2023-02-27 10:47 UTC, santhosh-thangavel commented on population-under-devolution-deal-in-england/population-under-devolution-deal-in-england.json
> +    "description": "## Percentage of the population living in an area covered by the highest level of devolution.  \nThe indicator is: Population under devolution deal in England.\nThe Levelling Up c
More information on Missions will be added once additional metadata is added in data dictionary. For now, I have added a comment.

2023-02-27 10:48 UTC, santhosh-thangavel commented on population-under-devolution-deal-in-england/population-under-devolution-deal-in-england.json
> +        "united-kingdom"
Added "misssion-12" in keywords

2023-02-27 10:53 UTC, canwaf commented
Closes #23

2023-02-27 11:27 UTC, sazzadur-ons commented on population-under-devolution-deal-in-england/population-under-devolution-deal-in-england.json
> +    "description": "## Percentage of the population living in an area covered by the highest level of devolution.  \nThe indicator is: Population under devolution deal in England.\nThe Levelling Up c
As we do not have more information about Mission numbering, you can remove 'The Mission is 12(expand with information on what mission 12 means)', and you can add 'The Mission number is 12'

2023-02-27 11:33 UTC, sazzadur-ons commented on population-under-devolution-deal-in-england/population-under-devolution-deal-in-england.json
> +    "summary": "Population under devolution deal in England",
Summary and title are same here. So I would be better to change summary slightly as follows:
"summary": "Percentage of the population living in an area under devolution deal in England"

2023-02-27 16:36 UTC, sazzadur-ons approved these changes

2023-02-27 17:14 UTC, merged