Homicide-offences
GSS-Cogs/provider-ons-ess pull request #56
Opened 2023-02-23 15:31 UTC by santhosh-thangavel

Added new qube-config file
Added warngling.py
Added a new csv file
Added metadata as well
Added Marker column for missing Observation values

#28

2023-02-28 12:06 UTC, abdulkasim1 requested changes

2023-02-28 12:50 UTC, santhosh-thangavel commented on homicide-offences/homicide-offences.json
> +    "description": "## Rate of Homicide offences per million population.  \nThe indicator is: Homicide.\nThe Levelling Up category is: Restoring a sense of community, local pride and belonging.  \nTh
Added "Rate of Homicide offences per million population in England and Wales" for summary

2023-02-28 12:50 UTC, santhosh-thangavel commented on homicide-offences/homicide-offences.json
> +    ],
Added "https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice" URL for themes

2023-02-28 12:51 UTC, santhosh-thangavel commented on homicide-offences/homicide-offences.json
> +            "measure":{
"data_type" : "float" is added now

2023-02-28 12:52 UTC, santhosh-thangavel commented on homicide-offences/homicide-offences.json
> +                "from_existing": "http://purl.org/linked-data/sdmx/2009/dimension#refPeriod",
```
"title":"Period"
"summary":"Period for Homicide offences in England and Wales"
```
is added

2023-03-01 12:03 UTC, abdulkasim1 requested changes

2023-03-01 12:03 UTC, abdulkasim1 commented on homicide-offences/homicide-offences.json
> +            },
Change label to just "Crime Rate".

2023-03-01 12:09 UTC, santhosh-thangavel commented on homicide-offences/homicide-offences.json
> +            },
Added label `"Crime Rate"`

2023-03-01 12:21 UTC, abdulkasim1 approved these changes

2023-03-01 12:25 UTC, merged